# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  cabrithonapiwebapi:
    image: cabrithonapiwebapi
    build:
      context: .
      dockerfile: src/CabriThonAPI.WebAPI/Dockerfile
    ports:
      - 5272:5272
